project_id = "giwalyevnaqfamswluya"

[functions.games]
verify_jwt = false

[functions.mobile-wall]
verify_jwt = true

[functions.mobile-circles]
verify_jwt = true

[functions.mobile-wall-post]
verify_jwt = true